### ISSUE TITLE
Update Funktion

### ISSUE THREAD

**Issue by cerdbrink** [amshove/gameserver_webinterface#31]
Vielleicht könnte man eine gewisse Datei oder script in dem Webinterface angeben. Über dieses kann man dann ein Spiel updaten.

Erspart den weg das man sich erst einloggen muss. Vielleicht direkt mit anschließenden rsync

**Comment by Torsten-** [comment]
Ich denke das macht das Update eher schwieriger, weil mit dem Aufruf des Scriptes ist es ja nicht getan - es gibt output der interessant sein könnte, es gibt evtl. Nachfragen vom Script und das Script könnte mit Fehlern abbrechen - all das müsste man abfangen und in die Webseite einbauen und damit interagieren.
Ich glaube da ist SSH schneller und einfacher, oder?

**Comment by cerdbrink** [comment]
Da hast du wohl recht. Die Idee sollte man aktuell auf eis legen
